version: '3.4'

services:
  mongo:
      restart: always
      image: mongo:bionic
      volumes:
        - ./datastores/mongo:/data/db
  postgres:
      restart: always
      image: postgres:alpine
      volumes:
        - ./datastores/postgres:/var/lib/postgresql/data
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "80:8000"
    depends_on:
      - mongo
      - postgres
