version: "2"

services:
    mongo:
        restart: always
        image: mongo:bionic
        ports:
            - 27017:27017
        volumes:
            - ./datastores/mongo:/data/db
    postgres:
        restart: always
        image: postgres:alpine
        ports:
            - 5432:5432
        volumes:
            - ./datastores/postgres/storage:/var/lib/postgresql/data
